UI improvements
aranja/tux pull request #88
Opened 2017-03-20 16:14 UTC by DavidBachmann

## TuxFab (Tux Floating Action Button)
**Normal**
![image](https://cloud.githubusercontent.com/assets/8494120/24205716/11725f2a-0f14-11e7-982d-603c225cd679.png)
**Hovered**
![image](https://cloud.githubusercontent.com/assets/8494120/24205723/1883c2e0-0f14-11e7-953b-42a344b9fa31.png)
**Items hovered**
![image](https://cloud.githubusercontent.com/assets/8494120/24205729/1eaca4ca-0f14-11e7-8bec-e979dda3f56d.png)
**Active**
![image](https://cloud.githubusercontent.com/assets/8494120/24205747/29c23b90-0f14-11e7-8d57-7f62c24ed84d.png)

## Material design inspired Tux UI components

### Sidebar update
![screen shot 2017-03-22 at 15 25 25](https://cloud.githubusercontent.com/assets/8494120/24205651/dff55c36-0f13-11e7-97f6-3a6e3b34872f.png)

### Buttons
**Normal**
![image](https://cloud.githubusercontent.com/assets/8494120/24145020/5d86c286-0e27-11e7-8207-b6d24acd2cdb.png)
**Hover**
![image](https://cloud.githubusercontent.com/assets/8494120/24145038/6caf4490-0e27-11e7-8c8e-f435439adc9c.png)

### Inputs
**Normal**
![image](https://cloud.githubusercontent.com/assets/8494120/24205819/610f7eb4-0f14-11e7-8ebd-730db4571f4e.png)
**Animates on focus**
![image](https://cloud.githubusercontent.com/assets/8494120/24205831/6c77185c-0f14-11e7-967c-7d1d3a42ccca.png)
**Same with TagEditor**
![image](https://cloud.githubusercontent.com/assets/8494120/24205859/7b5e00ec-0f14-11e7-9d07-74f235a42384.png)

2017-03-21 11:14 UTC, DavidBachmann commented
Extracted buttons into Button component that's inspired by material (you're welcome @eirikurn and @rthor)

**Normal**
![image](https://cloud.githubusercontent.com/assets/8494120/24145020/5d86c286-0e27-11e7-8207-b6d24acd2cdb.png)

**Hover**
![image](https://cloud.githubusercontent.com/assets/8494120/24145038/6caf4490-0e27-11e7-8c8e-f435439adc9c.png)

2017-03-21 11:33 UTC, eirikurn commented
Sweet!

I like the form buttons.

Good job with the fab, but we should rethink what functions we want inside it (they should be primary actions, consistent and have obvious icons), and where to move stuff that doesn't fit in the fab.

2017-03-21 11:43 UTC, eirikurn requested changes
Sweet. One bug in `Button`.

2017-03-21 11:43 UTC, eirikurn commented on packages/tux/src/components/Button/Button.tsx
> +const Button = ({ type, flat, themeColor, raised, onClick, children }: Button) => {
`onClick` isn't used.

2017-03-21 11:43 UTC, eirikurn commented on packages/tux/src/components/AlertBar/index.tsx
> +import { tuxColors } from '../../colors'
We should call this a `theme`, with a few semantic primary variables which apply to component specific variables. Something like:

```
export const Theme = {
  primary: 'pink',
  secondary: 'green',
  foreground: '#333',
  background: '#fff',
  altBackground: '#ddd',
  border: '#666',
}

export const Button = {
  primaryBG: Theme.primary,
  primaryBGHover: fade(Theme.primary, 0.9),
  secondaryBG: Theme.background,
  secondaryBGHover: Theme.altBackground,
  ...
}
```

Happy to discuss more or do this later.

2017-03-21 11:43 UTC, eirikurn commented on packages/tux/src/components/AlertBar/index.tsx
> +import { tuxColors } from '../../colors'
then later we can make helpers to edit this theme, either by changing main theme variables or going deeper.

2017-03-21 11:43 UTC, eirikurn commented on packages/tux/src/components/TuxFab/TuxFab.tsx
> +          </a>
Don't need to do this now, but if we end up using this, it should display the button label on hover and be optimised for touch.

2017-03-21 11:56 UTC, eirikurn commented
So I'm thinking that the FAB should have this primary action to toggle edit mode for the page. It would need some other icon, as the + is used for creating new things.

I imagine using secondary actions to add specific models. "Add Page", "Add Gallery Item", "Add News", and maybe a settings button to hide the rest in a modal.

My issues are:

* How does the user login. I haven't seen a login button in a FAB before.
* Having a FAB for user-provided actions (like "Create <model>") involves more work to give each fab a meaningful icon or background. This might be difficult for some models/users. Would a series of "+" actions with different labels work?

2017-03-22 15:32 UTC, DavidBachmann commented
Todo: When in admin mode and **not** logged in TuxFab should only be a log-in action.
Haven't been able to display the Fab when I'm not logged in.

2017-03-22 17:21 UTC, merged