Add model component
aranja/tux pull request #93
Opened 2017-03-24 10:15 UTC by baering

2017-03-27 12:12 UTC, eirikurn requested changes
Good first implementation. Some questions.

2017-03-27 12:12 UTC, eirikurn commented on packages/tux/src/components/fields/Input.tsx
> +    }
This constructor isn't doing anything, right?

2017-03-27 12:12 UTC, eirikurn commented on packages/tux/src/components/fields/Input.tsx
> +          value={value ? value : DEFAULT_VALUE}
`value={value || ''}` would also work :)

2017-03-27 12:12 UTC, eirikurn commented on packages/tux-adapter-contentful/src/locale.ts
> +    }
What was the issue with the existing syntax? Shouldn't it extract '' and 0 correctly?

2017-03-27 12:12 UTC, eirikurn commented on packages/tux-adapter-contentful/src/locale.ts
> +      }
This condition is also weird. `model.fields` is always Object.

2017-03-27 15:50 UTC, baering commented on packages/tux/src/components/fields/Input.tsx
> +          value={value ? value : DEFAULT_VALUE}
~I like the idea of each component having a default value constant~

Ah, you meant `value || DEFAULT_VALUE`? I can change that, I just know that @rthor loves ternary so much.

2017-03-27 15:51 UTC, baering commented on packages/tux/src/components/fields/Input.tsx
> +    }
Correct, forgot to remove - I think it served a purpose at some point but that was then refactored. Thanks.

2017-03-27 16:03 UTC, baering commented on packages/tux-adapter-contentful/src/locale.ts
> +    }
I'll revert this.

2017-03-27 16:10 UTC, baering commented on packages/tux-adapter-contentful/src/locale.ts
> +      }
This was missing a `model.fields[fieldName]`, I'll refactor this code.

2017-03-27 17:43 UTC, rthor commented on packages/tux/src/components/fields/Input.tsx
> +          value={value ? value : DEFAULT_VALUE}
Ternaries are fine. I was quoting someone in that conversion... But sometimes they are really confusing.

2017-03-28 10:02 UTC, eirikurn approved these changes
Can you resolve conflicts and merge.

2017-03-28 10:02 UTC, eirikurn commented on packages/tux-adapter-contentful/src/locale.ts
> +        injectedValue = fieldValue
The outer condition seems to be unnecessary.

2017-03-28 10:31 UTC, merged